- name: Generate distribution
  hosts: localhost
  gather_facts: false
  roles:
    - role: dist_generation
      tags: dist_generation

- name: Install ByzCast
  hosts: remote_hosts
  gather_facts: false
  roles:
    - role: byzcast_installation
      tags: byzcast_installation
  vars:
    dist_dir: "dist"
    remote_dest_dir: "byzcast"
    ansible_user: "agst"

- name: Execute ByzCast
  hosts: remote_hosts
  gather_facts: false
  roles:
    - role: byzcast_execution
      tags: byzcast_execution
  vars:
    ansible_user: "agst"
