- name: Generate dist
  hosts: localhost
  tasks:
    - name: Generate distribution
      ansible.builtin.command: python py/distribute.py
      changed_when: true

- name: Install byzcast on remote hosts
  hosts: remote_hosts
  vars:
    dist_dir: "dist"
    remote_dest_dir: "byzcast"
    ansible_user: "agst"
  tasks:
    - name: Sync dist folder
      ansible.posix.synchronize:
        src: "{{ dist_dir }}/"
        dest: "{{ remote_dest_dir }}/"
        delete: true

    - name: Ensure Java 21 is installed
      ansible.builtin.apt:
        name: openjdk-21-jdk
        state: present
        update_cache: true
      become: true

    - name: Kill existing byzcast processes
      changed_when: true
      ansible.builtin.shell: |
        kill $(pidof java) || true
      become: true

    - name: Run byzcast
      changed_when: true
      startbyzcast:
        gs: "{{ params }}"
