- name: Sync dist directory
  ansible.posix.synchronize:
    src: "{{ dist_dir }}/"
    dest: "{{ remote_dest_dir }}/"
    delete: true

- name: Ensure Java 21 is installed
  ansible.builtin.apt:
    name: openjdk-21-jdk
    state: present
    update_cache: true
  become: true
