package dev.agst.byzcast.message;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * Represents a response within the ByzCast protocol.
 *
 * <p>This sealed interface defines the structure of responses that can be sent within the ByzCast
 * system. Responses can be either {@link AggregatedResponse}, {@link GroupResponse}, or {@link
 * BatchResponse}.
 */
public sealed interface Response extends Serializable {

  /**
   * Represents an aggregated response generated by each node.
   *
   * <p>This record encapsulates the content of the response generated by a node. If the node
   * forwarded the request, it also includes the responses from downstream nodes in the {@code
   * downstreamResponses} list.
   *
   * @param content The content of the response generated by the node.
   * @param downstreamResponses A list of {@link GroupResponse} instances representing the responses
   *     from downstream nodes.
   */
  public static record AggregatedResponse(
      String content, ArrayList<GroupResponse> downstreamResponses) implements Response {}

  /**
   * Represents a response from a specific group in the ByzCast protocol.
   *
   * <p>This record helps identify which group replied with what response in the chain of forwarded
   * requests and responses.
   *
   * @param groupID The unique identifier of the group that generated the response.
   * @param response The {@link AggregatedResponse} generated by the group.
   */
  public static record GroupResponse(int groupID, AggregatedResponse response)
      implements Response {}

  /**
   * Represents a batch response within the ByzCast protocol.
   *
   * <p>This record encapsulates a batch of {@link AggregatedResponse} instances that are sent in
   * response to a batch request.
   *
   * @param responses A list of {@link AggregatedResponse} instances representing the responses to
   *     the batch request.
   */
  public static record BatchResponse(ArrayList<AggregatedResponse> responses) implements Response {}
}
